name: micrograd
channels:
  - anaconda
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.12
  - pytorch==2.5.1
  - torchvision
  - torchaudio
  - notebook
  - jupyterlab
  - voila
  - ipywidgets
  - graphviz
  - numpy
  - matplotlib
  - scikit-learn
  - graphviz
  - black
  - fsspec
  - sympy==1.13.1
